spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/interview
    username: interview
    password: jmXzj3eV#456jmXzj3eV
    hikari:
      maximum-pool-size: 6
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        hbm2ddl:
          auto: none
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.yml
jwt:
  signKey: 9tZOoGoKXM2iRv6/jYmXq/BRDQ7c10hstXzlJIgEByNUzTOVmQedbKKqAvX1O5yzlSvnHHi9zKq1FfyYIlR8IxxJ+CIKpTA+ARCuA9y5Zi4iBVqVkaOnndBJT5rXOgwczzRlXuYMGyS9cbmQ/4ceJtuopvtlwwwbhIInj4MZoRsaqYzvax8rZ0uNkI5Unk+zGHQeRs8dgJodlTdBJ/KuEjTeB+Fa7/Gc9J1BAgSSxYSNZWqP4eFS9hA7lWVnvjfevKutdczGUEiGkzURd4n3sJiE78kzRKHR//+noaZkNteSWDIWzTtrw1WV7gBL4XUPR6I5A9DpTbWKzJ/X1aYCMGIUgHX6pj6KQZTaxh3EG81gX/VimUvXrGrs0Zx+aE+YfvqjgC0V9Jp8j6mm6/1spuE8DyyY0xPQSXiUiF0PId9JhbQqiYvl4dhiBxDG4UcX0Oqf+G/BoaWscmAAZC9qIiPsvKiiQ22Zj5KaciP6xkogQi79JsLS6rtPgcfqq5KyAjNut0NPgeOr7mLkvy8RfP4s1HV5n5nGxIqBf+f76gKO5s1MSc2yy3Pp/z6AwbPsBQzslZouyFHExrhgquvMc02W+f+YkEYpTO8nSLEWlZctXytf4ZbnYGFx33qlrbaRxiaGfIMgxvr5iGMRxpx6saENzOCk9NSHTczCPUm3kngVrLEAWt1FjFAWl0fT2TPS